version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: 'mysql:latest'
    environment:
      # You should definitely change the password in production
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: qa_voter

